server:
  port: 8080

spring:
  cloud:
    gateway:
      default-filters:
        - StripPrefix=1
      routes:
        - id: upload_route
          uri: http://localhost:8081
          predicates:
            - Path=/api/v1/upload/**
        - id: stream_route
          uri: http://localhost:8081
          predicates:
            - Path=/api/v1/stream/**
