server:
  port: 8443
  ssl:
    enabled: true
    key-store: classpath:certs/gateway.p12
    key-store-password: yourKeystorePassword
    key-store-type: PKCS12
    key-alias: gateway

spring:
  cloud:
    gateway:
      default-filters:
        - StripPrefix=1
      routes:
        - id: auth_route
          uri: http://localhost:8081
          predicates:
            - Path=/api/v1/auth/**
        - id: upload_route
          uri: http://localhost:8081
          predicates:
            - Path=/api/v1/upload/**
        - id: stream_route
          uri: http://localhost:8081
          predicates:
            - Path=/api/v1/stream/**
  security:
    oauth2:
      resourceserver:
        jwt:
          # JWK Set URI 또는 공개 키 직접 지정
          # 예시) Auth 서버가 제공하는 JWK Set URI
          jwk-set-uri: https://auth.example.com/.well-known/jwks.json

logging:
  level:
    root: INFO
    com.example.vaultcast.gateway.LoggingFilter: DEBUG
    org.springframework.security.oauth2: DEBUG

jwt:
  secret: ChangeThisVerySecretKey1234567890
